### ISSUE TITLE
Test flakes in CI: Network Granular Checks: services

### ISSUE THREAD

**Issue by trozet** [ovn-kubernetes/ovn-kubernetes#1293]
We keep seeing these fail randomly in CI:

Summarizing 4 Failures:

[Fail] [sig-network] Networking Granular Checks: Services [It] should function for node-Service: udp 
/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/network/utils.go:381

[Fail] [sig-network] Networking Granular Checks: Services [It] should function for endpoint-Service: udp 
/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/network/utils.go:269

[Fail] [sig-network] Networking Granular Checks: Services [It] should update nodePort: udp [Slow] 
/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/network/utils.go:381

[Fail] [sig-network] Networking Granular Checks: Services [It] should function for pod-Service: udp 
/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/network/utils.go:269

Example:
https://github.com/ovn-org/ovn-kubernetes/pull/1288/checks?check_run_id=610671712

**Comment by danwinship** [comment]
Skimming those results quickly, it is the NodeIP checks that are failing, not ClusterIP, and they appear to be failing completely (the NodeIP does not reach any of the three Endpoints), meaning this has nothing to do with the very similar set of flakes in OpenShift with openshift-sdn (which is good because we were very certain that those flakes were VXLAN-related and wouldn't affect OVN).
